default_agent: agentcore_sre_container
agents:
  agentcore_sre_direct:
    name: agentcore_sre_direct
    language: python
    node_version: '20'
    entrypoint: /Users/vmuthusu/code/cisco/ai-defense-python-sdk/ai-defense-python-sdk/examples/agentsec/3-agent-runtimes/amazon-bedrock-agentcore/direct-deploy/agentcore_app.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_11
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/vmuthusu/code/cisco/ai-defense-python-sdk/ai-defense-python-sdk/examples/agentsec/3-agent-runtimes/amazon-bedrock-agentcore/direct-deploy
    aws:
      execution_role: arn:aws:iam::422940237045:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-778ad7f570
      execution_role_auto_create: false
      account: '422940237045'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-422940237045-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: false
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: agentcore_sre_direct-VTGjmnBNLY
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:422940237045:runtime/agentcore_sre_direct-VTGjmnBNLY
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_ONLY
      memory_id: agentcore_sre_direct_mem-1scWue4C9i
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:422940237045:memory/agentcore_sre_direct_mem-1scWue4C9i
      memory_name: agentcore_sre_direct_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  agentcore_sre_container:
    name: agentcore_sre_container
    language: python
    node_version: '20'
    entrypoint: container-deploy/agentcore_app.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: /Users/vmuthusu/code/cisco/ai-defense-python-sdk/ai-defense-python-sdk/examples/agentsec/3-agent-runtimes/amazon-bedrock-agentcore
    aws:
      execution_role: arn:aws:iam::422940237045:role/AmazonBedrockAgentCoreSDKRuntime-us-west-2-5a80f48d50
      execution_role_auto_create: false
      account: '422940237045'
      region: us-west-2
      ecr_repository: 422940237045.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-my_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: false
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: agentcore_sre_container-U6UOjbEndJ
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:422940237045:runtime/agentcore_sre_container-U6UOjbEndJ
      agent_session_id: 86461df8-4755-451b-91eb-cb748fd85654
    codebuild:
      project_name: bedrock-agentcore-agentcore_sre_container-builder
      execution_role: arn:aws:iam::422940237045:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-5a80f48d50
      source_bucket: bedrock-agentcore-codebuild-sources-422940237045-us-west-2
    memory:
      mode: STM_ONLY
      memory_id: agentcore_sre_container_mem-oHEfeC2nq6
      memory_arn: arn:aws:bedrock-agentcore:us-west-2:422940237045:memory/agentcore_sre_container_mem-oHEfeC2nq6
      memory_name: agentcore_sre_container_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
